### AUTH - POST - REGISTER
POST  http://{{hostname}}:{{port}}/auth/register
Content-Type: application/json

{
    "email" : "user6@test.com",
    "username" : "user6",
    "password" : "123456",
    "confirm_password" : "123456"
}

### AUTH - POST - LOGIN
# @name login
POST  http://{{hostname}}:{{port}}/auth/login
Content-Type: application/json

{
    "email_or_username" : "user@test.com",
    "password" : "123456"
}

### AUTH - GET - TOKEN
@authToken = {{login.response.body.data.access_token}}

GET  http://{{hostname}}:{{port}}/auth/token
Authorization: Bearer {{authToken}}